// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/enbility/ship-go/api"
	mock "github.com/stretchr/testify/mock"
)

// NewShipPairingServiceInterface creates a new instance of ShipPairingServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShipPairingServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShipPairingServiceInterface {
	mock := &ShipPairingServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ShipPairingServiceInterface is an autogenerated mock type for the ShipPairingServiceInterface type
type ShipPairingServiceInterface struct {
	mock.Mock
}

type ShipPairingServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *ShipPairingServiceInterface) EXPECT() *ShipPairingServiceInterface_Expecter {
	return &ShipPairingServiceInterface_Expecter{mock: &_m.Mock}
}

// CreateAnnouncer provides a mock function for the type ShipPairingServiceInterface
func (_mock *ShipPairingServiceInterface) CreateAnnouncer() api.PairingAnnouncerInterface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CreateAnnouncer")
	}

	var r0 api.PairingAnnouncerInterface
	if returnFunc, ok := ret.Get(0).(func() api.PairingAnnouncerInterface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.PairingAnnouncerInterface)
		}
	}
	return r0
}

// ShipPairingServiceInterface_CreateAnnouncer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAnnouncer'
type ShipPairingServiceInterface_CreateAnnouncer_Call struct {
	*mock.Call
}

// CreateAnnouncer is a helper method to define mock.On call
func (_e *ShipPairingServiceInterface_Expecter) CreateAnnouncer() *ShipPairingServiceInterface_CreateAnnouncer_Call {
	return &ShipPairingServiceInterface_CreateAnnouncer_Call{Call: _e.mock.On("CreateAnnouncer")}
}

func (_c *ShipPairingServiceInterface_CreateAnnouncer_Call) Run(run func()) *ShipPairingServiceInterface_CreateAnnouncer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ShipPairingServiceInterface_CreateAnnouncer_Call) Return(pairingAnnouncerInterface api.PairingAnnouncerInterface) *ShipPairingServiceInterface_CreateAnnouncer_Call {
	_c.Call.Return(pairingAnnouncerInterface)
	return _c
}

func (_c *ShipPairingServiceInterface_CreateAnnouncer_Call) RunAndReturn(run func() api.PairingAnnouncerInterface) *ShipPairingServiceInterface_CreateAnnouncer_Call {
	_c.Call.Return(run)
	return _c
}

// CreateListener provides a mock function for the type ShipPairingServiceInterface
func (_mock *ShipPairingServiceInterface) CreateListener() api.PairingListenerInterface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CreateListener")
	}

	var r0 api.PairingListenerInterface
	if returnFunc, ok := ret.Get(0).(func() api.PairingListenerInterface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.PairingListenerInterface)
		}
	}
	return r0
}

// ShipPairingServiceInterface_CreateListener_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateListener'
type ShipPairingServiceInterface_CreateListener_Call struct {
	*mock.Call
}

// CreateListener is a helper method to define mock.On call
func (_e *ShipPairingServiceInterface_Expecter) CreateListener() *ShipPairingServiceInterface_CreateListener_Call {
	return &ShipPairingServiceInterface_CreateListener_Call{Call: _e.mock.On("CreateListener")}
}

func (_c *ShipPairingServiceInterface_CreateListener_Call) Run(run func()) *ShipPairingServiceInterface_CreateListener_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ShipPairingServiceInterface_CreateListener_Call) Return(pairingListenerInterface api.PairingListenerInterface) *ShipPairingServiceInterface_CreateListener_Call {
	_c.Call.Return(pairingListenerInterface)
	return _c
}

func (_c *ShipPairingServiceInterface_CreateListener_Call) RunAndReturn(run func() api.PairingListenerInterface) *ShipPairingServiceInterface_CreateListener_Call {
	_c.Call.Return(run)
	return _c
}

// IsServiceRunning provides a mock function for the type ShipPairingServiceInterface
func (_mock *ShipPairingServiceInterface) IsServiceRunning() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsServiceRunning")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// ShipPairingServiceInterface_IsServiceRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsServiceRunning'
type ShipPairingServiceInterface_IsServiceRunning_Call struct {
	*mock.Call
}

// IsServiceRunning is a helper method to define mock.On call
func (_e *ShipPairingServiceInterface_Expecter) IsServiceRunning() *ShipPairingServiceInterface_IsServiceRunning_Call {
	return &ShipPairingServiceInterface_IsServiceRunning_Call{Call: _e.mock.On("IsServiceRunning")}
}

func (_c *ShipPairingServiceInterface_IsServiceRunning_Call) Run(run func()) *ShipPairingServiceInterface_IsServiceRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ShipPairingServiceInterface_IsServiceRunning_Call) Return(b bool) *ShipPairingServiceInterface_IsServiceRunning_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *ShipPairingServiceInterface_IsServiceRunning_Call) RunAndReturn(run func() bool) *ShipPairingServiceInterface_IsServiceRunning_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function for the type ShipPairingServiceInterface
func (_mock *ShipPairingServiceInterface) Shutdown() {
	_mock.Called()
	return
}

// ShipPairingServiceInterface_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type ShipPairingServiceInterface_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
func (_e *ShipPairingServiceInterface_Expecter) Shutdown() *ShipPairingServiceInterface_Shutdown_Call {
	return &ShipPairingServiceInterface_Shutdown_Call{Call: _e.mock.On("Shutdown")}
}

func (_c *ShipPairingServiceInterface_Shutdown_Call) Run(run func()) *ShipPairingServiceInterface_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ShipPairingServiceInterface_Shutdown_Call) Return() *ShipPairingServiceInterface_Shutdown_Call {
	_c.Call.Return()
	return _c
}

func (_c *ShipPairingServiceInterface_Shutdown_Call) RunAndReturn(run func()) *ShipPairingServiceInterface_Shutdown_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function for the type ShipPairingServiceInterface
func (_mock *ShipPairingServiceInterface) Start() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ShipPairingServiceInterface_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type ShipPairingServiceInterface_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *ShipPairingServiceInterface_Expecter) Start() *ShipPairingServiceInterface_Start_Call {
	return &ShipPairingServiceInterface_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *ShipPairingServiceInterface_Start_Call) Run(run func()) *ShipPairingServiceInterface_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ShipPairingServiceInterface_Start_Call) Return(err error) *ShipPairingServiceInterface_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ShipPairingServiceInterface_Start_Call) RunAndReturn(run func() error) *ShipPairingServiceInterface_Start_Call {
	_c.Call.Return(run)
	return _c
}
